pipeline {
  environment {
    imagename = "nginx"
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git([url: 'https://github.com/akanksha-rasala/Assignment-4.git', branch: 'main', credentialsId: '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'])

      }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build nginx
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push("$BUILD_NUMBER")
             dockerImage.push('latest')

          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $imagename:$BUILD_NUMBER"
         sh "docker rmi $imagename:latest"

      }
    }
  }
}
